homeSuccess:
  javascripts:
    - /application/webprefix
    - /gadgets/js/rpc.js?c=1
    - http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.2/prototype.js
    - /opOpenSocialPlugin/js/tabs-min
    - /opOpenSocialPlugin/js/container

profileSuccess:
  customize:
    profileApplication:
      template: [application, profileApplication]
      parts:    [profile]
      target:   [after]
  javascripts:
    - /application/webprefix
    - /gadgets/js/rpc.js?c=1
    - http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.2/prototype.js
    - /opOpenSocialPlugin/js/tabs-min
    - /opOpenSocialPlugin/js/container
