propel:
  _attributes: { package: plugins.opOpenSocialPlugin.lib.model }

  application:
    id: ~
    url: { type: varchar(128), required: true }
    culture: { type: varchar(7), required: true }
    title: { type: varchar(128) }
    directory_title : { type: varchar(128) }
    screenshot: { type: varchar(128) }
    thumbnail : { type: varchar(128) }
    author:  { type: varchar(128) }
    author_email: { type: varchar(128) }
    description: { type: longvarchar }
    settings: { type: longvarchar }
    views: { type: longvarchar }
    version: { type: varchar(64), required: true }
    height: { type: integer, required: true }
    scrolling: { type: integer, required: true }
    modified: { type: integer, required: true }

  application_setting:
    id: ~
    application_id: ~
    member_id: { type: integer, foreignTable: member, foreignReference: id }
    name: { type: varchar(128), required: true }
    value: { type: varchar(255), required: true }

  member_application:
    id: ~
    member_id: { type: integer, foreignTable: member, foreignReference: id }
    application_id: ~
