propel:
  _attributes: { package: plugins.opOpenSocialPlugin.lib.model }

  application:
    id: ~
    url: { type: varchar(128), required: true }
    height: { type: integer, required: true }
    scrolling: { type: integer, required: true }

  application_i18n:
    title: { type: varchar(128) }
    directory_title : { type: varchar(128) }
    screenshot: { type: varchar(128) }
    thumbnail : { type: varchar(128) }
    author:  { type: varchar(128) }
    author_email: { type: varchar(128) }
    description: { type: longvarchar }
    settings: { type: longvarchar }
    views: { type: longvarchar }
    version: { type: varchar(64), required: true }
    updated_at: ~

  application_setting:
    id: ~
    member_application_id: ~
    name: { type: varchar(128), required: true }
    value: { type: varchar(255), required: true }

  member_application:
    id: ~
    member_id: { type: integer, foreignTable: member, foreignReference: id }
    application_id: 
    is_disp_other: { type: boolean }
    is_disp_home: { type: boolean }
    sort_order: { type: integer }
