canvasSuccess:
  javascripts:
    - /application/js
    - /gadgets/js/rpc.js?c=1
    - http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.2/prototype.js
    - /plugins/opOpenSocialPlugin/js/tabs-min
    - /plugins/opOpenSocialPlugin/js/container

jsSuccess:
  has_layout: off
