listSuccess:
  stylesheets:
    - /opOpenSocialPlugin/css/opensocial

gallerySuccess:
  stylesheets:
    - /opOpenSocialPlugin/css/opensocial

canvasSuccess:
  javascripts:
    - /application/webprefix
    - /gadgets/js/rpc.js?c=1
    - http://ajax.googleapis.com/ajax/libs/prototype/1.6.0.2/prototype.js
    - /opOpenSocialPlugin/js/tabs-min
    - /opOpenSocialPlugin/js/container

jsSuccess:
  has_layout: off
